Demo_ManageRestauran/Demo_ManageRestauran/Models/DBContext.cs
using Microsoft.EntityFrameworkCore;


namespace Demo_ManageRestauran.Models
{
    public class DBContext : DbContext
    {
        public DBContext(DbContextOptions<DBContext> options) : base(options)
        {
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Food>(entity =>
            {
                entity.HasKey(e => e.FoodID);
                entity.Property(e => e.FoodID).HasColumnName("FoodID");
                entity.Property(e => e.FoodName).HasColumnName("FoodName");
                entity.Property(e => e.Description).HasColumnName("Description");
                entity.Property(e => e.Price).HasColumnName("Price");
            });
            //Sử dụng phương thức HasKey () để định cấu hình tên của ràng buộc khóa chính trong cơ sở dữ liệu.
            
            modelBuilder.Entity<Restauran>(entity =>
            {
                entity.HasKey(e => e.RestauranID);
                entity.Property(e => e.RestauranID).HasColumnName("Restaurent");
                entity.Property(e => e.RestauranName).HasColumnName("RestaurentName");
                entity.Property(e => e.Addr).HasColumnName("Addr");
                entity.Property(e => e.Phone).HasColumnName("Phone");
            });
            
            modelBuilder.Entity<FoodRestaurent>().HasKey(sc => new { sc.FoodID, sc.RestauranID });//các khóa ngoại phải là khóa chính tổng hợp trong bảng nối
            
            modelBuilder.Entity<FoodRestaurent>()
                .HasOne<Restauran>(sc => sc.Restauran)
                .WithMany(s => s.FoodRestaurents)
                .HasForeignKey(sc => sc.RestauranID);


            modelBuilder.Entity<FoodRestaurent>()
                .HasOne<Food>(sc => sc.Food)
                .WithMany(s => s.FoodRestaurents)
                .HasForeignKey(sc => sc.FoodID);
        }
        public DbSet<Food> Foods { get; set; }
        public DbSet<Restauran> Restaurans { get; set; }
        public DbSet<FoodRestaurent> FoodRestaurents { get; set; }
        
        
    }
}

Demo_ManageRestauran/Demo_ManageRestauran/Models/ErrorViewModel.cs
using System;

namespace Demo_ManageRestauran.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Demo_ManageRestauran/Demo_ManageRestauran/Models/Food.cs
using System.Collections.Generic;

namespace Demo_ManageRestauran.Models
{
    public class Food
    {
        public int FoodID { get; set; }
        public string FoodName { get; set; }
        public string Description { get; set; }
        public string Price { get; set; }
        
        public virtual ICollection<FoodRestaurent> FoodRestaurents { get; set; }
    }
}

Demo_ManageRestauran/Demo_ManageRestauran/Models/FoodRestaurent.cs
using System.Collections.Generic;

namespace Demo_ManageRestauran.Models
{
    public class FoodRestaurent
    {
        public int FoodRestaurentID { get; set; } 
        public int FoodID { get; set; }
        public Food Food { get; set; }
        
        public int RestauranID { get; set; }
        public Restauran Restauran { get; set; }
    }
}

Demo_ManageRestauran/Demo_ManageRestauran/Models/Restauran.cs
using System.Collections.Generic;

namespace Demo_ManageRestauran.Models
{
    public class Restauran
    {
        public int RestauranID { get; set; }
        public string RestauranName { get; set; }
        public string Addr { get; set; }
        public string Phone { get; set; }
        
        public virtual ICollection<FoodRestaurent> FoodRestaurents { get; set; }
    }
}

Demo_ManageRestauran/Demo_ManageRestauran/Controllers/FoodController.cs
using Demo_ManageRestauran.Models;
using Demo_ManageRestauran.Service.FoodService;
using Microsoft.AspNetCore.Mvc;

namespace Demo_ManageRestauran.Controllers
{
    public class FoodController : Controller
    {
        private IFoodService _FoodService;

        public FoodController(IFoodService classService)
        {
            _FoodService = classService;
        }
        
        // Get:Class/
        [HttpGet]
        public IActionResult Index()
        {
            return View(_FoodService.GetAll());
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Food food)
        {
            _FoodService.Add(food);
            _FoodService.Save();
            return RedirectToAction("Index");
        }
        
        [HttpGet]
        public IActionResult Edit(int id)
        {
            var getId = _FoodService.GetById(id);
            return View(getId);
        }
        
        [HttpPost]
        public IActionResult Edit(Food food)
        {
            _FoodService.Update(food);
            _FoodService.Save();
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Delete(int id)
        {
            _FoodService.Delete(id);
            _FoodService.Save();
            return RedirectToAction("Index");
        }
    }
    
}

Demo_ManageRestauran/Demo_ManageRestauran/Controllers/FoodRestaurentController.cs
using Demo_ManageRestauran.Service.FoodRestaurentService;
using Microsoft.AspNetCore.Mvc;

namespace Demo_ManageRestauran.Controllers
{
    public class FoodRestaurentController : Controller
    {
        private readonly IFoodRestaurantService _foodRestaurantService;

        public FoodRestaurentController(IFoodRestaurantService foodRestaurantService)
        {
            _foodRestaurantService = foodRestaurantService;
        }
        // GET
        [HttpGet]
        public IActionResult Index()
        {
            return View(_foodRestaurantService.GetAll());
        }
        
    }
}

Demo_ManageRestauran/Demo_ManageRestauran/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Demo_ManageRestauran.Models;

namespace Demo_ManageRestauran.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel {RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier});
        }
    }
}

Demo_ManageRestauran/Demo_ManageRestauran/Controllers/RestauranController.cs
using Demo_ManageRestauran.Models;
using Demo_ManageRestauran.Service.RestauranReponsitory;
using Microsoft.AspNetCore.Mvc;

namespace Demo_ManageRestauran.Controllers
{
    public class RestauranController : Controller
    {
        private IRestauranSerrvice _restauranSerrvice;

        public RestauranController(IRestauranSerrvice restauranSerrvice)
        {
            _restauranSerrvice = restauranSerrvice;
        }

        // GET
        public IActionResult Index()
        {
            return View(_restauranSerrvice.GetAll());
        }
        
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        
        [HttpPost]
        public IActionResult Create(Restauran restauran)
        {
            _restauranSerrvice.Add(restauran);
            _restauranSerrvice.Save();
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            var getId = _restauranSerrvice.GetById(id);
            return View(getId);
        }

        [HttpPost]
        public IActionResult Edit(Restauran restauran)
        {
            _restauranSerrvice.Update(restauran);
            _restauranSerrvice.Save();
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Delete(int id)
        {
            _restauranSerrvice.Delete(id);
            _restauranSerrvice.Save();
            return RedirectToAction("Index");
        }
    }
}

Demo_ManageRestauran/Demo_ManageRestauran/Views/Food/Create.cshtml
@model Demo_ManageRestauran.Models.Food

<!DOCTYPE html>
<html>
<head>
    <title>title</title>
</head>
<body>
<div class="container-fluid">
    <div class="row">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <form asp-action="Create">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="FoodName" class="control-label"></label>
                    <input asp-for="FoodName" class="form-control" />
                    <span asp-validation-for="FoodName" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Description" class="control-label"></label>
                    <input asp-for="Description" class="form-control" />
                    <span asp-validation-for="Description" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Price" class="control-label"></label>
                    <input asp-for="Price" class="form-control" />
                    <span asp-validation-for="Price" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input type="submit" value="Create" class="btn btn-primary" />
                    <a class="text-dark btn btn-primary" asp-area="" asp-controller="Food" asp-action="Index">Back</a>
                </div>
            </form>
        </div>
    </div>
</div>
</body>
</html>

Demo_ManageRestauran/Demo_ManageRestauran/Views/Food/Edit.cshtml
@model Demo_ManageRestauran.Models.Food

<!DOCTYPE html>

<html>
<head>
    <title>title</title>
</head>
<body>
<div class="container-fluid">
    <div class="row">
        <div class="col-lg-12 col-md-12 col-12">
            <form method="post" asp-controller="Food" asp-action="Edit">
                <input type="hidden" class="form-control" asp-for="FoodID">
                <div class="form-group">
                    <label asp-for="FoodName" class="control-label"></label>
                    <input asp-for="FoodName" class="form-control" />
                    <span asp-validation-for="FoodName" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Description" class="control-label"></label>
                    <input asp-for="Description" class="form-control" />
                    <span asp-validation-for="Description" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Price" class="control-label"></label>
                    <input asp-for="Price" class="form-control" />
                    <span asp-validation-for="Price" class="text-danger"></span>
                </div>
                
                <input class="btn btn-primary" type="submit" value="Save"/>
                <a class=" text-dark btn btn-primary" asp-area="" asp-controller="Food" asp-action="Index">Back</a>
            </form>
        </div>
    </div>
</div>

</body>
</html>

Demo_ManageRestauran/Demo_ManageRestauran/Views/Food/Index.cshtml
@model IEnumerable<Demo_ManageRestauran.Models.Food>

<!DOCTYPE html>

<html>
<head>
    <title>title</title>
</head>
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<script src='https://kit.fontawesome.com/a076d05399.js'></script>
<body>
<div class="x_content">
    <a asp-action="Create" class="btn btn-primary">Create <i class='fas fa-plus-square'></i></a>
    <table class="table">
        <thead>
        <tr style="color: red">
            <th> Name </th>
            <th > DEsc </th>
            <th> Giá </th>
        </tr>
        </thead>
        <tbody>
       @foreach (var item in Model)
        {
            <tr class="text-left">
                <td> @Html.DisplayFor(modelItem => item.FoodName)</td>
                <td> @Html.DisplayFor(modelItem => item.Description)</td>
                <td> @Html.DisplayFor(modelItem => item.Price)</td>

                <td>
                    <a class="btn btn-primary" asp-action="Edit" asp-route-id="@item.FoodID">Edit <i class="fa fa-edit"></i></a>
                    <a class="btn btn-primary" asp-action="Delete" asp-route-id="@item.FoodID">Delete <i class="fa fa-trash"></i></a>
                    @* <a class="btn btn-primary" asp-action="Delete" asp-route-id="@item.StudentID” onclick=“return confirm('bạn có chắc chắn muốn xóa');">Delete</a> *@
                </td>
            </tr>
        }

        </tbody>
    </table>
</div>
</body>
</html>

Demo_ManageRestauran/Demo_ManageRestauran/Views/FoodRestaurent/Index.cshtml
@model IEnumerable<Demo_ManageRestauran.Models.FoodRestaurent>

<!DOCTYPE html>

<html>
<head>
    <title>title</title>
</head>
<body>
<div>
    <table class="table">
        <thead>
        <tr style="color: red">
            <th> Name </th>
            <th > DEsc </th>
          </tr>
        </thead>
        <tbody>
        @foreach (var item in Model)
        {
            <tr class="text-left">
                <td> @Html.DisplayFor(modelItem => item.FoodID)</td>
                <td> @Html.DisplayFor(modelItem => item.RestauranID)</td>
                <td>
                    @*<a class="btn btn-primary" asp-action="Edit" asp-route-id="@item.FoodID">Edit <i class="fa fa-edit"></i></a>
                    <a class="btn btn-primary" asp-action="Delete" asp-route-id="@item.FoodID">Delete <i class="fa fa-trash"></i></a>*@
                    @* <a class="btn btn-primary" asp-action="Delete" asp-route-id="@item.StudentID” onclick=“return confirm('bạn có chắc chắn muốn xóa');">Delete</a> *@
                </td>
            </tr>
        }

        </tbody>
    </table>
</div>
</body>
</html>

Demo_ManageRestauran/Demo_ManageRestauran/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Demo_ManageRestauran/Demo_ManageRestauran/Views/Restauran/Create.cshtml
@model Demo_ManageRestauran.Models.Restauran

<!DOCTYPE html>
<html>
<head>
    <title>title</title>
</head>
<body>
<div class="container-fluid">
    <div class="row">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <form asp-action="Create">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="RestauranName" class="control-label"></label>
                    <input asp-for="RestauranName" class="form-control" />
                    <span asp-validation-for="RestauranName" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Addr" class="control-label"></label>
                    <input asp-for="Addr" class="form-control" />
                    <span asp-validation-for="Addr" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Phone" class="control-label"></label>
                    <input asp-for="Phone" class="form-control" />
                    <span asp-validation-for="Phone" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input type="submit" value="Create" class="btn btn-primary" />
                    <a class="text-dark btn btn-primary" asp-area="" asp-controller="Restauran" asp-action="Index">Back</a>
                </div>
            </form>
        </div>
    </div>
</div>
</body>
</html>

Demo_ManageRestauran/Demo_ManageRestauran/Views/Restauran/Edit.cshtml
@model Demo_ManageRestauran.Models.Restauran

<!DOCTYPE html>

<html>
<head>
    <title>title</title>
</head>
<body>
<div>
      
</div>
</body>
</html>

Demo_ManageRestauran/Demo_ManageRestauran/Views/Restauran/Index.cshtml
@model IEnumerable<Demo_ManageRestauran.Models.Restauran>

<!DOCTYPE html>
<html>
<head>
    <title>title</title>
</head>
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<script src='https://kit.fontawesome.com/a076d05399.js'></script>
<script src="https://use.fontawesome.com/49b98aaeb5.js"></script>
<body>
<div class="x_content">

    <a asp-action="Create" class="btn btn-primary">Create <i class='fas fa-plus-square'></i></a>
    <table class="table">
        <thead>
        <tr style="color: red">
            <th> Name </th>
            <th > Addr </th>
            <th> Phone </th>
        </tr>
        </thead>
        <tbody>

        @foreach (var item in Model)
        {
            <tr class="text-left">
                <td> @Html.DisplayFor(modelItem => item.RestauranName)</td>
                <td> @Html.DisplayFor(modelItem => item.Addr)</td>
                <td> @Html.DisplayFor(modelItem => item.Phone)</td>

                <td>
                    <a class="btn btn-primary" asp-action="Edit" asp-route-id="@item.RestauranID">Edit <i class="fa fa-edit"></i></a>
                    <a class="btn btn-primary" asp-action="Delete" asp-route-id="@item.RestauranID">Delete <i class="fa fa-trash"></i></a>
                    @* <a class="btn btn-primary" asp-action="Delete" asp-route-id="@item.StudentID” onclick=“return confirm('bạn có chắc chắn muốn xóa');">Delete</a> *@
                </td>
            </tr>
        }

        </tbody>
    </table>
</div>
</body>
</html>

Demo_ManageRestauran/Demo_ManageRestauran/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Demo_ManageRestauran</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"/>
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Demo_ManageRestauran</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Food" asp-action="Index">Food</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Restauran" asp-action="Index">Restauran</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="FoodRestaurent" asp-action="Index">FoodRestaurent</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - Demo_ManageRestauran - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>